$$L=
\left(\begin{matrix} 
L_{0,0} & 0 & 0\\
L_{1,0} & L_{11}& 0\\
L_{2,0} &L_{2,1}& L_{2,2}
\end{matrix}  \right)
$$

$$U=
\left(\begin{matrix}  
1 & U_{0,1} & U_{0,2}\\ 
0 & 1 & U_{1,2} \\
0 & 0 &  1
\end{matrix}\right)
$$

$$A=
\left(\begin{matrix}  
a_{0,0} & a_{0,1} & a_{0,2}\\ 
a_{1,0} & a_{1,1} & a_{1,2} \\
a_{2,0} & a_{2,1} & a_{2,2}
\end{matrix}\right)
$$

$$L\,U=A$$




$$L=
\left(\begin{matrix} 
a_{0,0} & 0 & 0\\
a_{1,0} & a_{1,1}-L_{1,0}U_{0,1}& 0\\
a_{2,1} &a_{2,1}-L_{2,0}U_{0,1}& a_{2,2}-L_{2,0}U_{0,2}-L_{2,1}U_{1,2}        
\end{matrix}  \right)
$$


$$U=
\left(\begin{matrix}  
1 & \dfrac{a_{0,1}}{a_{0,0}} & \dfrac{a_{0,2}}{a_{0,0}}\\ 
0 & 1 & \dfrac{a_{1,2}-L_{1,0}U_{0,2}}{L_{1,1}} \\
0 & 0 &  1
\end{matrix}\right)
$$

**Paso 1:**
> $\text{para}\, i = 0\ldots n$

$$
L_{i,0} = A_{i,0}\\
U_{i,i} = 1.0
$$

> $\text{para}\, j = 1\ldots n$

$$ 
U_{0,j}=\dfrac{A_{0,j}}{A_{0,0}}
$$

**Paso 2**

> $\text{para}\, j = 1\ldots n$

>> $\text{para}\, i = j\ldots n$

$$
L_{i,j}=A_{i,j}-\sum_{k=1}^{j-1}{U_{k,j}L_{i,k}} 
$$

$$
U_{j,k}=\dfrac{1}{L_{j,j}}\left(A_{j,k}-\sum_{i=1}^{j-1}{U_{i,k}L_{j,i}}\right)\, \text{para}\, k = j\ldots n
$$

In [47]:
import numpy as np
A=np.array([[4.0,-9.0,2.0],[2.0,-4.0,6.0],[1.0,-1.0,3.0]])
b= np.array([[5.0],[3],[4]])
print(A, b)

(array([[ 4., -9.,  2.],
       [ 2., -4.,  6.],
       [ 1., -1.,  3.]]), array([[5.],
       [3.],
       [4.]]))


In [62]:
n,m = np.shape(A)
L = np.zeros_like(A)
U = np.zeros_like(A)
for i in range(n):
    L[i,0] = A[i,0]
    U[i,i] = 1.0
    if i > 0:
        U[0,i] = A[0,i] / A[0,0]
    
for j in range (1, n):  
    for i in range(j,n):
        L[i,j] = A[i,j]
        
        for k in range(j-1):  
            L[i,j] = L[i,j] - L[i,k]*U[k,j]
            
    for k in range(j+1,n):  
        U[j,k] = A[j,k] 
        
        for i in range (j-1):
            U[j,k] = U[j,k] - L[j,i]*U[i,k] 
                        
        U[j,k] = U[j,k] / L[j,j]      

In [63]:
L

array([[ 4. ,  0. ,  0. ],
       [ 2. , -4. ,  0. ],
       [ 1. , -1. ,  2.5]])

In [64]:
U

array([[ 1.  , -2.25,  0.5 ],
       [ 0.  ,  1.  , -1.5 ],
       [ 0.  ,  0.  ,  1.  ]])

In [82]:
from scipy.linalg import lu, lu_factor, lu_solve

scipy.linalg.lu
scipy.linalg.lu(a, permute_l=False, overwrite_a=False, check_finite=True)[source]
Compute pivoted LU decompostion of a matrix.

The decomposition is:

A = P L U
where P is a permutation matrix, L lower triangular with unit diagonal elements, and U upper triangular.

Parameters:	
a : (M, N) array_like

Array to decompose

permute_l : bool

Perform the multiplication P*L (Default: do not permute)

overwrite_a : bool

Whether to overwrite data in a (may improve performance)

check_finite : boolean, optional

Whether to check that the input matrix contains only finite numbers. Disabling may give a performance gain, but may result in problems (crashes, non-termination) if the inputs do contain infinities or NaNs.

Returns:	
(If permute_l == False)

p : (M, M) ndarray

Permutation matrix

l : (M, K) ndarray

Lower triangular or trapezoidal matrix with unit diagonal. K = min(M, N)

u : (K, N) ndarray

Upper triangular or trapezoidal matrix

(If permute_l == True)

pl : (M, K) ndarray

Permuted L matrix. K = min(M, N)

u : (K, N) ndarray

Upper triangular or trapezoidal matrix

In [83]:
Ps,Ls,Us =lu(A, permute_l=False, overwrite_a=False, check_finite=True)

In [84]:
Ps

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [85]:
Ls

array([[1.  , 0.  , 0.  ],
       [0.25, 1.  , 0.  ],
       [0.5 , 0.4 , 1.  ]])

In [86]:
Us

array([[ 4.  , -9.  ,  2.  ],
       [ 0.  ,  1.25,  2.5 ],
       [ 0.  ,  0.  ,  4.  ]])

In [87]:
lu, piv = lu_factor(A)

In [88]:
lu

array([[ 4.  , -9.  ,  2.  ],
       [ 0.25,  1.25,  2.5 ],
       [ 0.5 ,  0.4 ,  4.  ]])

In [89]:
piv

array([0, 2, 2])

In [90]:
x = lu_solve((lu, piv), b)

In [91]:
print x

[[ 6.95]
 [ 2.5 ]
 [-0.15]]


scipy.linalg.lu_solve(lu_and_piv, b, trans=0, overwrite_b=False, check_finite=True)[source]
Solve an equation system, a x = b, given the LU factorization of a

Parameters
(lu, piv)
Factorization of the coefficient matrix a, as given by lu_factor

barray
Right-hand side

trans{0, 1, 2}, optional
Type of system to solve:

trans

system

0

a x = b

1

a^T x = b

2

a^H x = b

overwrite_bbool, optional
Whether to overwrite data in b (may increase performance)

check_finitebool, optional
Whether to check that the input matrices contain only finite numbers. Disabling may give a performance gain, but may result in problems (crashes, non-termination) if the inputs do contain infinities or NaNs.

Returns
xarray
Solution to the system